-- Migration V1: Criação das tabelas do domínio Tool

CREATE TABLE tb_tool(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL
);

CREATE TABLE tb_tool_item_status(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(50) NOT NULL
);

CREATE TABLE tb_tool_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id VARCHAR(255) NOT NULL,
    color VARCHAR(50),
    tool_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    CONSTRAINT fk_tool_item_to_tool FOREIGN KEY(tool_id) REFERENCES tb_tool(id),
    CONSTRAINT fk_tool_item_to_status FOREIGN KEY(status_id) REFERENCES tb_tool_item_status(id)
);